// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "FluidInterface.h"

FluidInterface::FluidInterface() {
  { m_window1 = new Fl_Double_Window(997, 656, "window1");
    m_window1->user_data((void*)(this));
    { m_btn_load_data = new Fl_Button(350, 510, 75, 55, "Load historical data");
      m_btn_load_data->align(Fl_Align(FL_ALIGN_WRAP));
    } // Fl_Button* m_btn_load_data
    { m_starting_bid = new Fl_Value_Input(700, 510, 45, 20, "Starting Bid");
      m_starting_bid->labelsize(10);
      m_starting_bid->textsize(10);
    } // Fl_Value_Input* m_starting_bid
    { m_curr_ask = new Fl_Value_Input(700, 535, 45, 20, "Current Ask");
    } // Fl_Value_Input* m_curr_ask
    { m_top_limit = new Fl_Value_Input(915, 510, 45, 20, "Top Limit");
    } // Fl_Value_Input* m_top_limit
    { m_top_profit = new Fl_Value_Input(915, 560, 45, 20, "Profit at top lim");
    } // Fl_Value_Input* m_top_profit
    { m_table = new Fl_Table(65, 0, 940, 495);
      m_table->labelsize(10);
      m_table->end();
    } // Fl_Table* m_table
    { m_curr_bid = new Fl_Value_Input(700, 560, 45, 20, "Current Bid");
    } // Fl_Value_Input* m_curr_bid
    { m_bottom_limit = new Fl_Value_Input(915, 535, 45, 20, "Bottom Limit");
    } // Fl_Value_Input* m_bottom_limit
    { m_bottom_profit = new Fl_Value_Input(915, 585, 45, 20, "Profit at bottom lim");
    } // Fl_Value_Input* m_bottom_profit
    { m_btn_up = new Fl_Button(545, 510, 65, 40, "Up");
    } // Fl_Button* m_btn_up
    { m_btn_down = new Fl_Button(545, 565, 65, 40, "Down");
    } // Fl_Button* m_btn_down
    { m_btn_next = new Fl_Button(445, 510, 80, 55, "Next");
    } // Fl_Button* m_btn_next
    { m_btn_initAlgo = new Fl_Button(350, 575, 80, 55, "Initialize Algo");
      m_btn_initAlgo->align(Fl_Align(FL_ALIGN_WRAP));
    } // Fl_Button* m_btn_initAlgo
    { m_set_startBid = new Fl_Button(750, 510, 40, 20, "Set");
    } // Fl_Button* m_set_startBid
    { m_set_topLimit = new Fl_Button(965, 510, 40, 20, "Set");
    } // Fl_Button* m_set_topLimit
    { m_set_btmLimit = new Fl_Button(965, 535, 40, 20, "Set");
    } // Fl_Button* m_set_btmLimit
    { m_slider1 = new Fl_Value_Slider(5, 0, 35, 650, "m_slider1");
      m_slider1->minimum(200);
      m_slider1->maximum(0);
      m_slider1->step(1);
      m_slider1->value(100);
    } // Fl_Value_Slider* m_slider1
    { m_btn_extra = new Fl_Button(190, 575, 80, 55, "Extra");
    } // Fl_Button* m_btn_extra
    m_window1->end();
  } // Fl_Double_Window* m_window1
  { m_window2 = new Fl_Double_Window(502, 336, "window2");
    m_window2->user_data((void*)(this));
    { text_display = new Fl_Text_Display(80, 40, 325, 255, "text");
    } // Fl_Text_Display* text_display
    m_window2->end();
  } // Fl_Double_Window* m_window2
}
