// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef FluidPriceControl_h
#define FluidPriceControl_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Value_Slider.H>

class FluidPriceControlUI {
public:
  FluidPriceControlUI();
  Fl_Double_Window *mWindow;
  Fl_Button *mBtnUp;
  Fl_Button *mBtnDown;
  Fl_Output *mBidDisplay;
  Fl_Output *mAskDisplay;
  Fl_Value_Slider *mSlider;
  Fl_Button *mBtnLiveDataConsolePrint;
  Fl_Button *mBtnConnectLiveData;
  Fl_Button *mBtnStartLoop;
  Fl_Button *mBtnExperiment;
};
#endif
