// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "FluidControlInterface.h"

FluidControlInterface::FluidControlInterface() {
  { mWindow = new Fl_Double_Window(252, 210, "Control Interface");
    mWindow->user_data((void*)(this));
    { mWindowBox = new Fl_Box(5, 5, 90, 30, "Show Windows:");
      mWindowBox->align(Fl_Align(FL_ALIGN_WRAP));
    } // Fl_Box* mWindowBox
    { mBtnShowPositions1 = new Fl_Button(5, 35, 90, 40, "Positions1");
    } // Fl_Button* mBtnShowPositions1
    { mBtnShowPositions2 = new Fl_Button(5, 75, 90, 40, "Positions2");
    } // Fl_Button* mBtnShowPositions2
    { mBtnShowPositions3 = new Fl_Button(5, 115, 90, 40, "Positions3");
    } // Fl_Button* mBtnShowPositions3
    { mBtnShowPositions4 = new Fl_Button(5, 155, 90, 50, "Show Data Control Window");
      mBtnShowPositions4->align(Fl_Align(FL_ALIGN_WRAP));
    } // Fl_Button* mBtnShowPositions4
    { mBtnStartLoop = new Fl_Button(110, 15, 90, 40, "Start Loop");
    } // Fl_Button* mBtnStartLoop
    { mBtnStopLoop = new Fl_Button(110, 55, 90, 40, "Stop Loop");
    } // Fl_Button* mBtnStopLoop
    mWindow->end();
    mWindow->resizable(mWindow);
  } // Fl_Double_Window* mWindow
}
