// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef FluidControlInterface_h
#define FluidControlInterface_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>

class FluidControlInterface {
public:
  FluidControlInterface();
  Fl_Double_Window *mWindow;
  Fl_Box *mWindowBox;
  Fl_Button *mBtnShowPositions1;
  Fl_Button *mBtnShowPositions2;
  Fl_Button *mBtnShowPositions3;
  Fl_Button *mBtnShowPositions4;
  Fl_Button *mBtnStartLoop;
  Fl_Button *mBtnStopLoop;
};
#endif
