// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "FluidPriceControl.h"

FluidPriceControlUI::FluidPriceControlUI() {
  { mWindow = new Fl_Double_Window(230, 624, "Price Control");
    mWindow->user_data((void*)(this));
    { mBtnUp = new Fl_Button(50, 500, 60, 50, "Up");
    } // Fl_Button* mBtnUp
    { mBtnDown = new Fl_Button(50, 565, 60, 50, "Down");
    } // Fl_Button* mBtnDown
    { mBidDisplay = new Fl_Output(55, 450, 45, 20, "Bid");
      mBidDisplay->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Output* mBidDisplay
    { mAskDisplay = new Fl_Output(55, 405, 45, 20, "Ask");
      mAskDisplay->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Output* mAskDisplay
    { mSlider = new Fl_Value_Slider(10, 15, 35, 585, "Bid/Ask");
      mSlider->minimum(200);
      mSlider->maximum(0);
      mSlider->step(1);
      mSlider->value(100);
      mSlider->textsize(14);
    } // Fl_Value_Slider* mSlider
    { mBtnLiveDataConsolePrint = new Fl_Button(55, 155, 60, 50, "Print LiveData Console");
      mBtnLiveDataConsolePrint->labelsize(12);
      mBtnLiveDataConsolePrint->align(Fl_Align(FL_ALIGN_WRAP));
    } // Fl_Button* mBtnLiveDataConsolePrint
    { mBtnConnectLiveData = new Fl_Button(55, 215, 60, 50, "Connect Live Data");
      mBtnConnectLiveData->align(Fl_Align(FL_ALIGN_WRAP));
    } // Fl_Button* mBtnConnectLiveData
    { mBtnStartLoop = new Fl_Button(55, 90, 60, 50, "Start Loop");
      mBtnStartLoop->align(Fl_Align(FL_ALIGN_WRAP));
    } // Fl_Button* mBtnStartLoop
    { mBtnExperiment = new Fl_Button(65, 15, 90, 40, "Experiment");
    } // Fl_Button* mBtnExperiment
    mWindow->end();
  } // Fl_Double_Window* mWindow
}
