// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef CFluidInputUI_h
#define CFluidInputUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Input.H>

class CFluidInputUI {
public:
  CFluidInputUI();
  Fl_Double_Window *mWindow1;
  Fl_Button *mOkButton;
  Fl_Input *mInputField;
};
#endif
