// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "CFluidInputUI.h"

CFluidInputUI::CFluidInputUI() {
  { mWindow1 = new Fl_Double_Window(335, 47);
    mWindow1->user_data((void*)(this));
    { mOkButton = new Fl_Button(270, 0, 65, 40, "OK");
    } // Fl_Button* mOkButton
    { mInputField = new Fl_Input(5, 20, 265, 25, "Please Enter value:");
      mInputField->align(Fl_Align(FL_ALIGN_TOP_LEFT));
    } // Fl_Input* mInputField
    mWindow1->end();
  } // Fl_Double_Window* mWindow1
}
