// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef FluidControlInterface_h
#define FluidControlInterface_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>

class FluidControlInterface {
public:
  FluidControlInterface();
  Fl_Double_Window *m_window1;
  Fl_Button *m_btnShowPositions1;
  Fl_Box *m_windowBox;
  Fl_Button *m_btnShowPositions2;
  Fl_Button *m_btnShowPositions3;
  Fl_Button *m_btnShowPositions4;
  Fl_Button *m_btnExperiment1;
  Fl_Button *m_btnExperiment2;
};
#endif
