// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef FluidPosOrdManualUI_h
#define FluidPosOrdManualUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Table.H>

class FluidPosOrdManualUI {
public:
  FluidPosOrdManualUI();
  Fl_Double_Window *mWindow1;
  Fl_Table *mTable;
};
#endif
