// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "FluidSimpleTableWindow.h"

FluidSimpleTableWindow::FluidSimpleTableWindow() {
  { mwindow1 = new Fl_Double_Window(545, 514);
    mwindow1->user_data((void*)(this));
    { mTable = new Fl_Table(0, 0, 550, 520);
      mTable->end();
    } // Fl_Table* mTable
    mwindow1->end();
  } // Fl_Double_Window* mwindow1
}
