// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "FluidControlInterface.h"

FluidControlInterface::FluidControlInterface() {
  { m_window1 = new Fl_Double_Window(249, 172, "Control Interface");
    m_window1->user_data((void*)(this));
    { m_btnShowPositions1 = new Fl_Button(40, 25, 90, 40, "Positions1");
    } // Fl_Button* m_btnShowPositions1
    { m_windowBox = new Fl_Box(65, 0, 140, 20, "Show Windows:");
    } // Fl_Box* m_windowBox
    { m_btnShowPositions2 = new Fl_Button(135, 25, 90, 40, "Positions2");
    } // Fl_Button* m_btnShowPositions2
    { m_btnShowPositions3 = new Fl_Button(40, 70, 90, 40, "Positions3");
    } // Fl_Button* m_btnShowPositions3
    { m_btnShowPositions4 = new Fl_Button(135, 70, 90, 40, "Positions4");
    } // Fl_Button* m_btnShowPositions4
    { m_btnExperiment1 = new Fl_Button(40, 120, 90, 40, "Experiment 1");
    } // Fl_Button* m_btnExperiment1
    { m_btnExperiment2 = new Fl_Button(135, 120, 90, 40, "Experiment 2");
    } // Fl_Button* m_btnExperiment2
    m_window1->end();
  } // Fl_Double_Window* m_window1
}
