// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "FluidPosOrdManualUI.h"

FluidPosOrdManualUI::FluidPosOrdManualUI() {
  { mWindow1 = new Fl_Double_Window(958, 1008);
    mWindow1->user_data((void*)(this));
    { mTable = new Fl_Table(0, 0, 960, 1010);
      mTable->end();
    } // Fl_Table* mTable
    mWindow1->end();
  } // Fl_Double_Window* mWindow1
}
