// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "FluidPriceControl.h"

FluidPriceControlUI::FluidPriceControlUI() {
  { m_window1 = new Fl_Double_Window(193, 618, "Price Control");
    m_window1->user_data((void*)(this));
    { m_btnUp = new Fl_Button(50, 500, 60, 50, "Up");
    } // Fl_Button* m_btnUp
    { m_btnDown = new Fl_Button(50, 565, 60, 50, "Down");
    } // Fl_Button* m_btnDown
    { m_BidDisplay = new Fl_Output(55, 450, 45, 20, "Bid");
      m_BidDisplay->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Output* m_BidDisplay
    { m_AskDisplay = new Fl_Output(55, 405, 45, 20, "Ask");
      m_AskDisplay->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Output* m_AskDisplay
    { m_slider1 = new Fl_Value_Slider(10, 15, 35, 585, "Bid/Ask");
      m_slider1->minimum(200);
      m_slider1->maximum(0);
      m_slider1->step(1);
      m_slider1->value(100);
      m_slider1->textsize(14);
    } // Fl_Value_Slider* m_slider1
    { m_btnPrint = new Fl_Button(120, 500, 60, 50, "Print");
    } // Fl_Button* m_btnPrint
    m_window1->end();
  } // Fl_Double_Window* m_window1
}
