// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef FluidSimpleTableWindow_h
#define FluidSimpleTableWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Table.H>

class FluidSimpleTableWindow {
public:
  FluidSimpleTableWindow();
  Fl_Double_Window *mwindow1;
  Fl_Table *mTable;
};
#endif
