// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef FluidPriceControl_h
#define FluidPriceControl_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Value_Slider.H>

class FluidPriceControlUI {
public:
  FluidPriceControlUI();
  Fl_Double_Window *m_window1;
  Fl_Button *m_btnUp;
  Fl_Button *m_btnDown;
  Fl_Output *m_BidDisplay;
  Fl_Output *m_AskDisplay;
  Fl_Value_Slider *m_slider1;
  Fl_Button *m_btnPrint;
  Fl_Button *m_btnLiveDataConsolePrint;
  Fl_Button *m_btnConnectLiveData;
  Fl_Button *m_btnStartLoop;
  Fl_Button *m_btnExperiment;
};
#endif
