// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "FluidControlInterface.h"

FluidControlInterface::FluidControlInterface() {
  { m_window1 = new Fl_Double_Window(260, 211, "Control Interface");
    m_window1->user_data((void*)(this));
    { m_btnShowPositions1 = new Fl_Button(5, 35, 90, 40, "Positions1");
    } // Fl_Button* m_btnShowPositions1
    { m_windowBox = new Fl_Box(5, 5, 90, 30, "Show Windows:");
      m_windowBox->align(Fl_Align(FL_ALIGN_WRAP));
    } // Fl_Box* m_windowBox
    { m_btnShowPositions2 = new Fl_Button(5, 75, 90, 40, "Positions2");
    } // Fl_Button* m_btnShowPositions2
    { m_btnShowPositions3 = new Fl_Button(5, 115, 90, 40, "Positions3");
    } // Fl_Button* m_btnShowPositions3
    { m_btnShowPositions4 = new Fl_Button(5, 155, 90, 50, "Show Data Control Window");
      m_btnShowPositions4->align(Fl_Align(FL_ALIGN_WRAP));
    } // Fl_Button* m_btnShowPositions4
    { btnStartLoop = new Fl_Button(110, 15, 90, 40, "Start Loop");
    } // Fl_Button* btnStartLoop
    { btnStopLoop = new Fl_Button(110, 55, 90, 40, "Stop Loop");
    } // Fl_Button* btnStopLoop
    m_window1->end();
  } // Fl_Double_Window* m_window1
}
